env:
  node              : true
  browser           : true
  es2021            : true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

overrides           : []

parserOptions:
  ecmaVersion       : "latest"
  sourceType        : "module"
  project:
   - tsconfig.json

root: true

rules:
  semi               : [ 2, "never" ]
  one-var            : off
  return-await       : off
  indent             : off
  no-multi-spaces    : off
  operator-linebreak : off
  array-bracket-spacing:
    - "error"
    - "always"
  key-spacing:
    - "error"
    - multiLine:
        beforeColon : false
        afterColon  : true
      align:
        beforeColon : true
        afterColon  : true
  comma-style:
    - "error"
    - "last"
    - exceptions:
        VariableDeclaration: true
  "@typescript-eslint/indent": off
  "@typescript-eslint/return-await": [ 1, "in-try-catch" ]
  "@typescript-eslint/no-base-to-string": off
  "@typescript-eslint/naming-convention": off
  "@typescript-eslint/no-unused-vars":
    - "error"
    - varsIgnorePattern: "^_"
  "@typescript-eslint/no-invalid-void-type":
    - "error"
    - allowInGenericTypeArguments: true
  "@typescript-eslint/type-annotation-spacing":
    - "error"
    - before        : true
      after         : true
      overrides:
        arrow:
          before    : true
          after     : true
  "@typescript-eslint/key-spacing": off
  "@typescript-eslint/consistent-type-imports": off

ignorePatterns:
  - coverage
  - dist
  - test
  - rollup.config.ts
