env:
  node    : true,
  browser : true,
  es2021  : true

extends:
  - standard-with-typescript
  - prettier

overrides: []

parserOptions:
  ecmaVersion : latest,
  sourceType  : module,
  project:
   - tsconfig.json

rules:
  semi         : [ 2, never ]
  one-var      : off,
  return-await : off,
  "@typescript-eslint/return-await": [ 1, in-try-catch ]

ignorePatterns":
  - build, 
  - coverage, 
  - dist, 
  - test,
